### ISSUE TITLE
Styled scrollbar is affecting the accessibility of the website

### ISSUE THREAD

**Issue by Sadeedpv** [pratyushtiwary/devty#27]
Styled scrollbar is confusing and could affect the accessibility of the website. Maybe, we should revert it back to normal

**Comment by Sadeedpv** [comment]
Hey, I would love to work on this issue for hacktoberfest

**Comment by pratyushtiwary** [comment]
Okay, I actually changed it because it looked bad on Electron. Feel free to update the scrollbar.

This issue is very simple to fix so I'll not be assigning it `hacktoberfest` tag.

Let me know if you are still willing to work on this.

**Comment by sricharanandra** [comment]
Hey! I can do this. Should I change the style of the scrollbar to something similar but still a custom one to keep with the color schema and style of the website?

**Comment by pratyushtiwary** [comment]
Yes, try to keep it so that it looks good in electron builds as well. Also please make sure to use CSS variables, all variables can be found inside `src/assets/base.css`. Feel free to be creative just make sure it doesn't stand out too much and fits the overall look of the website.

To test on electron do the following:
1. Run `npm run build`,
2. Run `npm run electron:dev`

**Comment by sricharanandra** [comment]
@pratyushtiwary Trying to test my changes, but is there any way to test my changes live as opposed to running `npm run build` and `npm run electron:dev` everytime I want to see my style changes? It is getting quite tedious to build everytime I change colors or sizes

**Comment by pratyushtiwary** [comment]
You can test it directly on your browser using `npm run dev`, if it looks fine there it'll look fine in electron as well.
